# config.yaml
embedding_provider: local        # local | gemini

local:
  model_name: paraphrase-multilingual-MiniLM-L12-v2
  # model_name: all-mpnet-base-v2 # Alternative English-only model
  device: auto                   # mps | cpu | cuda | auto
  batch_size: 64

gemini:
  model_name: gemini-embedding-exp-03-07 # embedding-001
  api_key: AIzaSyAAKZmqTYC6jHzuXiyqVMwHaB-NWtDsvgQ         # Replace with your actual key or set GAI_API_KEY env var
  batch_size: 32

index:
  type: faiss                    # faiss | annoy (Annoy not implemented in this example)
  factory: FlatL2 #IVF256_HNSW32         # Faiss index factory string
  nprobe: 16                     # Faiss nprobe parameter for IVF indexes

rerank:
  enable: false
  local_model: cross-encoder/ms-marco-MiniLM-L-6-v2
  oversample: 4  # number of candidates per topk (reduce to e.g. 2 for fewer rerank API calls)
  gemini_model: gemini-2.0-flash-lite  # ← ここでモデル名を指定
  # Gemini rerank uses the same API key as embedding

output:
  top_k: 50
  dir: output                   # Directory to save results 