# config_high_quality_gemini.yaml
# embedding_provider is always gemini now
cache_dir: cache            # Query Embedding, Clustering, Explanation cache directory (Added explanation here)

gemini:
  model_name: models/text-embedding-004
  batch_size: 10
  # API key read from environment variable GEMINI_API_KEY

index:
  factory: HNSW32
  nprobe: 32

rerank:
  enable: false
  oversample: 4
  gemini_model: gemini-2.0-flash-lite
  use_local_fallback: false

cluster:
  algorithm: hdbscan
  min_cluster_size: 40
  label_model: gemini-2.0-flash-lite

output:
  top_k: 200
  dir: output

# --- Paper Explanation Settings ---
explanation:
  enable: true              # Enable the explanation feature in HTML output
  model_name: gemini-2.5-pro-exp-03-25 #gemini-2.0-flash-lite # LLM for generating explanations (Fallback if Files API fails)
  target_language: English # Target language for explanations (e.g., "English", "Japanese")
  cache_dir: explanation_cache # Subdirectory within the main cache_dir for explanations
  precompute: false         # Generate explanations during the main run (requires API calls)
  use_files_api: true       # NEW: Use Files API for PDF processing (preferred)
  files_api_model: gemini-2.5-pro-exp-03-25 # gemini-2.0-flash-lite # Model for Files API (can handle large context)
  files_api_prompt_template: |
    この PDF 論文を{target_language}で 要約してください。
    以下のセクションを含めてください:
    あなたは研究論文要約のプロフェッショナルです。以下のスタイルを厳守し、内容をわかりやすく簡潔に紹介する文章を生成してください。

    1段落目：課題提起と問題点を示しつつ、提案手法名（もしあれば）を明示する。  
    2段落目以降：提案手法の核心となるアルゴリズムや仕組みを具体的に解説する。数式の使用はできるだけ避け、言葉でわかりやすく説明する。
    最終段落：手法の価値や今後の課題を専門的な見地から深い洞察に基づいて考察して述べる。  
    全文で500〜1000字程度で、3〜4段落程度にまとめる。
    マークダウン形式で記述してください。タイトルは含めないでください。

  files_api_generation_config:
    temperature: 1
    top_p: 0.95
    max_output_tokens: 65536
  # Simple prompt template (can be customized) - Fallback if Files API fails or disabled

  # Simple prompt template (can be customized) - Fallback if Files API fails or disabled
  prompt_template: |
    以下の論文について、主要な貢献と新規性を中心に{target_language}で簡潔に解説してください。
    Title: {title}
    Abstract: {abstract}
    

# --- Fetch settings ---
fetch:
  arxiv:
    categories:
      - "cs.AI"
      - "cs.LG"
      - "cs.CV"
      - "cs.CL"
      - "cs.GR"
      - "cs.HC"
      - "stat.ML"
      - "q-bio.NC"
      - "q-bio.QM"
    max_results_per_category: 300 # Maximum results to fetch for all arXiv categories (note: arxiv API's max_results is global not per category)
    days_back: 1 # Number of days back to fetch papers from

  biorxiv:
    categories:
      - "neuroscience"
      - "bioinformatics"
      # - "genomics"
      - "evolutionary biology"
      # - "microbiology"
      - "synthetic biology"
      - "systems biology"
      - "animal behavior and cognition"
      # - "biochemistry"
      # - "bioengineering"
      # - "biophysics"
      # - "cancer biology"
      # - "cell biology"
      # - "clinical trials"
      # - "developmental biology"
      # - "ecology"
      # - "epidemiology"
      # - "genetics"
      # - "immunology"
      # - "medical informatics"
      # - "molecular biology"
      # - "paleontology"
      # - "pathology"
      # - "pharmacology and toxicology"
      # - "physiology"
      # - "plant biology"
      # - "scientific communication and education"
      # - "zoology"
    max_results_per_category: 100 # Maximum results to fetch per category
    days_back: 1 # Number of days back to fetch papers from (e.g., 1 means yesterday)

# Local BibTeX file settings
# ... existing code ...